"""empty message

Revision ID: 3ea2afc736cf
Revises: d0a2dc97cd37
Create Date: 2019-12-05 14:43:02.148989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea2afc736cf'
down_revision = 'd0a2dc97cd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('imported_from', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'imported_from')
    # ### end Alembic commands ###
