"""empty message

Revision ID: 4741f8a59d4e
Revises: 891c1d1e8077
Create Date: 2019-11-20 23:11:17.172942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4741f8a59d4e'
down_revision = '891c1d1e8077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_credentials',
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_gmail_id', sa.String(length=120), nullable=False),
    sa.Column('user_gmail_credentials', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('user_email'),
    sa.UniqueConstraint('user_gmail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gmail_credentials')
    # ### end Alembic commands ###
