"""empty message

Revision ID: 4907c596c00f
Revises: 
Create Date: 2019-12-03 00:44:43.168535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4907c596c00f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('email_templates', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email_templates', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.drop_column('email_templates', 'owner')
    op.drop_column('email_templates', 'name')
    # ### end Alembic commands ###
