"""empty message

Revision ID: 4f4f05756baa
Revises: bab3fa9d6c1f
Create Date: 2019-12-05 15:55:39.684552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4f05756baa'
down_revision = 'bab3fa9d6c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('owner_name_uc', 'email_templates', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('owner_name_uc', 'email_templates', ['owner', 'name'])
    # ### end Alembic commands ###
