"""empty message

Revision ID: 5881f1886327
Revises: 
Create Date: 2019-12-09 19:48:03.741643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5881f1886327'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('body', sa.VARCHAR(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.CheckConstraint('char_length(name) > 0', name='name_min_length'),
    sa.CheckConstraint('char_length(subject) > 0', name='subject_min_length'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('steps', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'steps', 'templates', ['template_id'], ['id'])
    op.drop_column('steps', 'email_template_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('email_template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.drop_column('steps', 'template_id')
    op.drop_table('templates')
    # ### end Alembic commands ###
