"""empty message

Revision ID: 632e26f84d61
Revises: c64b459d7677
Create Date: 2019-11-25 21:56:53.112533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632e26f84d61'
down_revision = 'c64b459d7677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('et_type', sa.String(length=120), nullable=True))
    op.drop_column('email_templates', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('type', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('email_templates', 'et_type')
    # ### end Alembic commands ###
