"""empty message

Revision ID: 6609680af56b
Revises: 65fd511f6dce
Create Date: 2019-11-19 15:48:54.195682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6609680af56b'
down_revision = '65fd511f6dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tests_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Tests_pkey')
    )
    # ### end Alembic commands ###
