"""empty message

Revision ID: 682f7a25068a
Revises: 
Create Date: 2019-11-19 21:36:13.382158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682f7a25068a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fName', sa.String(length=120), nullable=True),
    sa.Column('lName', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
