"""empty message

Revision ID: 6a7d85c1aa50
Revises: 
Create Date: 2019-11-20 22:40:24.698706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7d85c1aa50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gmail_credentials',
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('gmail_user_id', sa.String(length=120), nullable=False),
    sa.Column('gmail_credentials', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('user_email'),
    sa.UniqueConstraint('gmail_user_id')
    )
    op.drop_table('Tests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tests_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Tests_pkey')
    )
    op.drop_table('gmail_credentials')
    op.drop_table('users')
    # ### end Alembic commands ###
