"""empty message

Revision ID: 6bb94de53a71
Revises: cba47331e6be
Create Date: 2019-12-05 14:50:11.900294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb94de53a71'
down_revision = 'cba47331e6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_constraint('email_templates_step_id_fkey', 'email_templates', type_='foreignkey')
    op.drop_column('email_templates', 'step_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('email_templates_step_id_fkey', 'email_templates', 'steps', ['step_id'], ['id'])
    op.drop_column('email_templates', 'date_created')
    # ### end Alembic commands ###
