"""empty message

Revision ID: 9045474be291
Revises: 
Create Date: 2019-12-03 19:22:30.440931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9045474be291'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_templates', 'name')
    # ### end Alembic commands ###
