"""empty message

Revision ID: 94df9136b86f
Revises: 
Create Date: 2019-12-05 20:27:55.411908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94df9136b86f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'email_template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'email_template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
