"""empty message

Revision ID: bab3fa9d6c1f
Revises: 6bb94de53a71
Create Date: 2019-12-05 15:45:47.605436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab3fa9d6c1f'
down_revision = '6bb94de53a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'steps', 'email_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.drop_column('steps', 'template_id')
    # ### end Alembic commands ###
