"""empty message

Revision ID: bc16f425b50d
Revises: 
Create Date: 2019-11-22 12:44:34.032286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc16f425b50d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns_prospects',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], )
    )
    op.drop_constraint('prospects_email_key', 'prospects', type_='unique')
    op.add_column('users', sa.Column('gmail_address', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('gmail_auth_state', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('gmail_credentials', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_credentials')
    op.drop_column('users', 'gmail_auth_state')
    op.drop_column('users', 'gmail_address')
    op.create_unique_constraint('prospects_email_key', 'prospects', ['email'])
    op.drop_table('campaigns_prospects')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
