"""empty message

Revision ID: c2614fd7d527
Revises: 
Create Date: 2019-12-04 18:15:53.944339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2614fd7d527'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('email_templates', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_unique_constraint('owner_name_uc', 'email_templates', ['owner', 'name'])
    op.create_foreign_key(None, 'email_templates', 'users', ['owner'], ['id'])
    op.drop_column('prospects', 'imported_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('imported_from', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.drop_constraint('owner_name_uc', 'email_templates', type_='unique')
    op.drop_column('email_templates', 'owner')
    op.drop_column('email_templates', 'name')
    # ### end Alembic commands ###
