"""empty message

Revision ID: cba47331e6be
Revises: 
Create Date: 2019-12-05 12:44:53.743096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba47331e6be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('email_templates', sa.Column('step_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('owner_name_uc', 'email_templates', ['owner', 'name'])
    op.create_foreign_key(None, 'email_templates', 'users', ['owner'], ['id'])
    op.create_foreign_key(None, 'email_templates', 'steps', ['step_id'], ['id'])
    op.drop_constraint('steps_email_template_id_fkey', 'steps', type_='foreignkey')
    op.drop_column('steps', 'email_template_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('email_template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('steps_email_template_id_fkey', 'steps', 'email_templates', ['email_template_id'], ['id'])
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.drop_constraint('owner_name_uc', 'email_templates', type_='unique')
    op.drop_column('email_templates', 'step_id')
    op.drop_column('email_templates', 'owner')
    # ### end Alembic commands ###
