"""empty message

Revision ID: e3768a929e7a
Revises: 
Create Date: 2019-12-08 16:22:28.219619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3768a929e7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps_prospects',
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], )
    )
    op.alter_column('steps', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('steps_prospects')
    # ### end Alembic commands ###
